# Generated by Django 4.1.1 on 2022-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('temprature', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('humidity', models.CharField(max_length=200)),
                ('pressure', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('sunrise', models.CharField(max_length=200)),
                ('sunset', models.CharField(max_length=200)),
                ('windspeed', models.CharField(max_length=200)),
            ],
        ),
    ]
