# Generated by Django 4.1.1 on 2022-09-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dec',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
